# Generated by Django 4.2.11 on 2024-03-26 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Age', models.PositiveIntegerField(max_length=3, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)])),
                ('Total Cholesterol (mg/dL)', models.PositiveIntegerField(choices=[(159, 'Less than 160'), (160, '160 - 199'), (200, '200 - 239'), (240, '240 - 279'), (280, '280+')], max_length=3)),
                ('HDL Cholesterol (mg/dL)', models.PositiveIntegerField(choices=[(159, 'Less than 160'), (160, '160 - 199'), (200, '200 - 239'), (240, '240 - 279'), (280, '280+')], max_length=2)),
                ('Systolic Blood Pressure (mmHg)', models.PositiveIntegerField(choices=[(119, 'Less than 120'), (120, '120 - 129'), (130, '130 - 139'), (140, '140 - 159'), (160, '160 - 179'), (180, '180+')], max_length=3)),
                ('Smoker', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
            ],
        ),
    ]
