# Generated by Django 4.2.11 on 2024-03-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Total Cholesterol (mg/dL)',
            field=models.PositiveIntegerField(blank=True, choices=[(159, 'Less than 160'), (160, '160 - 199'), (200, '200 - 239'), (240, '240 - 279'), (280, '280+')], null=True),
        ),
    ]
