# Generated by Django 4.2.11 on 2024-03-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='HDL Cholesterol (mg/dL)',
            field=models.PositiveIntegerField(blank=True, choices=[(159, 'Less than 160'), (160, '160 - 199'), (200, '200 - 239'), (240, '240 - 279'), (280, '280+')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Smoker',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Systolic Blood Pressure (mmHg)',
            field=models.PositiveIntegerField(blank=True, choices=[(119, 'Less than 120'), (120, '120 - 129'), (130, '130 - 139'), (140, '140 - 159'), (160, '160 - 179'), (180, '180+')], null=True),
        ),
    ]
