# Generated by Django 4.2.11 on 2024-03-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_patient_hdl_cholesterol_mg_dl__and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="Age",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="Gender",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="HDL Cholesterol (mg/dL)",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="Smoker",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="Systolic Blood Pressure (mmHg)",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="Total Cholesterol (mg/dL)",
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_pressure",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (119, "Less than 120"),
                    (120, "120 - 129"),
                    (130, "130 - 139"),
                    (140, "140 - 159"),
                    (160, "160 - 179"),
                    (180, "180 and above"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="hdl_cholesterol",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (39, "Less than 40"),
                    (40, "40 - 49"),
                    (50, "50 - 59"),
                    (60, "60 and above"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="total_cholesterol",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (159, "Less than 160"),
                    (160, "160 - 199"),
                    (200, "200 - 239"),
                    (240, "240 - 279"),
                    (280, "280 and above"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="smoker",
            field=models.CharField(
                blank=True,
                choices=[("YES", "Yes"), ("NO", "No")],
                max_length=3,
                null=True,
            ),
        ),
    ]
