# Generated by Django 4.2.11 on 2024-03-29 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_patient_age_remove_patient_gender_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="age",
            new_name="AGE",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="blood_pressure",
            new_name="Blood_Pressure",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="gender",
            new_name="GENDER",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="hdl_cholesterol",
            new_name="HDL_Cholesterol",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="smoker",
            new_name="Smoker",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="total_cholesterol",
            new_name="Total_Cholestrol",
        ),
    ]
