# Generated by Django 4.2.11 on 2024-03-29 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_rename_age_patient_age_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="AGE",
            new_name="Age",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="GENDER",
            new_name="Gender",
        ),
    ]
