# Generated by Django 4.2.11 on 2024-03-29 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_rename_age_patient_age_rename_gender_patient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="Record_Timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
