# Generated by Django 4.2.11 on 2024-03-29 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_patient_record_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="Record_Timestamp",
        ),
    ]
