# Generated by Django 4.2.11 on 2024-03-29 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_remove_patient_record_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="Age",
            new_name="AGE",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="Gender",
            new_name="GENDER",
        ),
    ]
