# Generated by Django 4.2.11 on 2024-03-29 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_rename_age_patient_age_rename_gender_patient_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="Age",
            new_name="age",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="Blood_Pressure",
            new_name="blood_pressure",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="Gender",
            new_name="gender",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="HDL_Cholesterol",
            new_name="hdl_cholesterol",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="Smoker",
            new_name="is_smoker",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="Total_Cholestrol",
            new_name="total_cholestrol",
        ),
    ]
