# Generated by Django 4.2.11 on 2024-03-29 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_rename_age_patient_age_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="hdl_cholesterol",
            new_name="hdl_cholestrol",
        ),
    ]
