# Generated by Django 4.2.11 on 2024-03-29 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_rename_hdl_cholesterol_patient_hdl_cholestrol"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="hdl_cholestrol",
            new_name="hdl_cholesterol",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="total_cholestrol",
            new_name="total_cholesterol",
        ),
    ]
