# Generated by Django 4.2.11 on 2024-03-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_alter_patient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="risk",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
