# Generated by Django 4.2.11 on 2024-03-30 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_patient_risk"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
