# Generated by Django 4.2.11 on 2024-03-30 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_patient_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="patient",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
