# Generated by Django 4.2.11 on 2024-04-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0021_remove_patient_timestamp_patient_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="is_smoker",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=3,
                null=True,
            ),
        ),
    ]
